# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'AzureConnection'
  webAppName: 'serko-testcase'
  resourcrGroupName: 'serko-testcase'
  subID: '34d6d065-e2e4-466b-8978-d2e76aaf094f'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: DotNetCoreHelloWorld/WebApi.csproj
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: $(azureSubscription)
    WebAppName: $(webAppName)
    Package: $(System.ArtifactsDirectory)/**/*.zip
    takeAppOfflineFlag: true
    
- task: PowerShell@2
  inputs:
    targetType: inline
    script: '$api=Get-AzureRmResource -ResourceType "Microsoft.ApiManagement/service" -ResourceGroupName $(resourcrGroupName) -ResourceName $(webAppName)'
    script: '$api.Properties.provisioningState'
    #script: 'ARMClient GET /subscriptions/$(SubID)/resourceGroups/$(resourcrGroupName)/providers/Microsoft.ResourceHealth/availabilityStatuses?api-version=2015-01-01'
    errorActionPreference: 'continue'
